name: build toolchain

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mipsel-linux-uclibc, mipsel-linux-musl, mipsel-linux-uclibc-gcc7, mipsel-linux-musl-gcc7, mipsel-linux-uclibc-gcc10, mipsel-linux-musl-gcc10]
    steps:
      - uses: actions/checkout@main
      - name: Prepare environment
        run: |
          sudo apt-get update && sudo apt-get install -y unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Build toolchain
        run: |
          make CT_TARGET=${CT_TARGET}
          cd toolchain-mipsel
          tar cJf ../${CT_TARGET}.tar.xz *
        env:
          CT_TARGET: ${{ matrix.target }}
        working-directory: toolchain
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}
          path: toolchain/${{ matrix.target }}.tar.xz
      - uses: ncipollo/release-action@main
        with:
          tag: toolchain
          artifacts: toolchain/${{ matrix.target }}.tar.xz
          allowUpdates: true
          omitBodyDuringUpdate: true